alias rsync-copy="rsync -avz --progress -h"
alias rsync-move="rsync -avz --progress -h --remove-source-files"
alias rsync-update="rsync -avzu --progress -h"
alias rsync-synchronize="rsync -avzu --delete --progress -h"
alias rsync-dry="rsync -avzn --out-format='%o:%f:Last Modified %M'"
alias rsync-dry="rsync -rvzn --out-format='%o:%f'"
