# ============= SYSTEMCTL ALIASES ===============
alias xmr-enable="systemctl enable xmr-server.service"
alias xmr-disable="systemctl disable xmr-server.service"
alias xmr-stop="systemctl stop xmr-server.service"
alias xmr-start="systemctl start xmr-server.service"
alias xmr-status="systemctl status xmr-server.service"
alias xmr-restart="systemctl restart xmr-server.service"

alias jellyfin-enable="systemctl enable jellyfin.service"
alias jellyfin-disable="systemctl disable jellyfin.service"
alias jellyfin-stop="systemctl stop jellyfin.service"
alias jellyfin-start="systemctl start jellyfin.service"
alias jellyfin-status="systemctl status jellyfin.service"
alias jellyfin-restart="systemctl restart jellyfin.service"

alias deluged-enable="sudo systemctl enable deluged.service"
alias deluged-disable="sudo systemctl disable deluged.service"
alias deluged-stop="sudo systemctl stop deluged.service"
alias deluged-start="sudo systemctl start deluged.service"
alias deluged-status="sudo systemctl status deluged.service"
alias deluged-restart="sudo systemctl restart deluged.service"

#alias deluge-web-enable="sudo systemctl enable deluge-web.service"
#alias deluge-web-disable="sudo systemctl disable deluge-web.service"
#alias deluge-web-stop="sudo systemctl stop deluge-web.service"
#alias deluge-web-start="sudo systemctl start deluge-web.service"
#alias deluge-web-status="sudo systemctl status deluge-web.service"
#alias deluge-web-restart="sudo systemctl restart deluge-web.service"

alias smb-enable="systemctl enable smb.service"
alias smb-disable="systemctl disable smb.service"
alias smb-stop="systemctl stop smb.service"
alias smb-start="systemctl start smb.service"
alias smb-status="systemctl status smbd.service"
alias smb-restart="systemctl restart smb.service"

alias xrdp-enable="systemctl enable xrdp.service"
alias xrdp-disable="systemctl disable xrdp.service"
alias xrdp-stop="systemctl stop xrdp.service"
alias xrdp-start="systemctl start xrdp.service"
alias xrdp-status="systemctl status xrdp.service"
alias xrdp-restart="systemctl restart xrdp.service"

alias apache-enable="sudo systemctl enable apache2.service"
alias apache-disable="sudo systemctl disable apache2.service"
alias apache-stop="sudo systemctl stop apache2.service"
alias apache-start="sudo systemctl start apache2.service"
alias apache-status="sudo systemctl status apache2.service"
alias apache-restart="sudo systemctl restart apache2.service"

alias httpd-enable="sudo systemctl enable httpd.service"
alias httpd-disable="sudo systemctl disable httpd.service"
alias httpd-stop="sudo systemctl stop httpd.service"
alias httpd-start="sudo systemctl start httpd.service"
alias httpd-status="sudo systemctl status httpd.service"
alias httpd-restart="sudo systemctl restart httpd.service" 

alias minidlna-enable="sudo systemctl enable minidlna.service"
alias minidlna-disable="sudo systemctl disable minidlna.service"
alias minidlna-stop="sudo systemctl stop minidlna.service"
alias minidlna-start="sudo systemctl start minidlna.service"
alias minidlna-status="sudo systemctl status minidlna.service"
alias minidlna-restart="sudo systemctl stop minidlna.service;wait;sudo systemctl start minidlna.service"    

alias incrond-disable="sudo systemctl disable incrond.service"
alias incrond-enable="sudo systemctl enable incrond.service"
alias incrond-start="sudo systemctl start incrond.service"
alias incrond-status="sudo systemctl status incrond.service"
alias incrond-restart="sudo systemctl restart incrond.service"
alias incrond-disable="sudo systemctl disable incrond.service"
alias incrond-enable="sudo systemctl enable incrond.service"

alias lighttpd-stop="sudo systemctl stop lighttpd.service"
alias lighttpd-start="sudo systemctl start lighttpd.service"
alias lighttpd-status="sudo systemctl status lighttpd.service"
alias lighttpd-restart="sudo systemctl restart lighttpd.service"
alias lighttpd-disable="sudo systemctl disable lighttpd.service"
alias lighttpd-enable="sudo systemctl enable lighttpd.service"

alias nginx-stop="sudo systemctl stop nginx.service"
alias nginx-start="sudo systemctl start nginx.service"
alias nginx-status="sudo systemctl status nginx.service"
alias nginx-restart="sudo systemctl restart nginx.service"
alias nginx-disable="sudo systemctl disable nginx.service"
alias nginx-enable="sudo systemctl enable nginx.service"

alias openvpn-stop="sudo systemctl stop openvpn@chicago.service"
alias openvpn-start="sudo systemctl start openvpn@chicago.service"
alias openvpn-status="sudo systemctl status openvpn@chicago.service"
alias openvpn-restart="sudo systemctl restart openvpn@chicago.service"
alias openvpn-disable="sudo systemctl disable openvpn@chicago.service"
alias openvpn-enable="sudo systemctl enable openvpn@chicago.service"

#alias teamviewer-stop="sudo systemctl stop teamviewerd.service"
#alias teamviewer-start="sudo systemctl start teamviewerd.service"
#alias teamviewer-status="sudo systemctl status teamviewerd.service"
#alias teamviewer-restart="sudo systemctl restart teamviewerd.service"
#alias teamviewer-disable="sudo systemctl disable teamviewerd.service"
#alias teamviewer-enable="sudo systemctl enable teamviewerd.service"

alias nfs-stop="sudo systemctl stop nfs-server.service"
alias nfs-start="sudo systemctl start nfs-server.service"
alias nfs-status="sudo systemctl status nfs-server.service"
alias nfs-restart="sudo systemctl restart nfs-server.service"
alias nfs-disable="sudo systemctl disable nfs-server.service"
alias nfs-enable="sudo systemctl enable nfs-server.service"

alias caddy-stop="sudo systemctl stop caddy"
alias caddy-start="sudo systemctl start caddy"
alias caddy-status="sudo systemctl status caddy"
alias caddy-restart="sudo systemctl restart caddy"
alias caddy-disable="sudo systemctl disable caddy"
alias caddy-enable="sudo systemctl enable caddy"

alias t-stop="sudo systemctl stop transmission-daemon"
alias t-start="sudo systemctl start transmission-daemon"
alias t-status="sudo systemctl status transmission-daemon"
alias t-restart="sudo systemctl restart transmission-daemon"
alias t-disable="sudo systemctl disable transmission-daemon"
alias t-enable="sudo systemctl enable transmission-daemon"

alias hotspot-stop="sudo systemctl stop hostapd.service"
alias hotspot-start="sudo systemctl start hostapd.service"
alias hotspot-status="sudo systemctl status hostapd.service"
alias hotspot-restart="sudo systemctl restart hostapd.service"
alias hotspot-disable="sudo systemctl disable hostapd.service"
alias hotspot-enable="sudo systemctl enable hostapd.service"

alias docker-stop="sudo systemctl stop docker.service"
alias docker-start="sudo systemctl start docker.service"
alias docker-status="sudo systemctl status docker.service"
alias docker-restart="sudo systemctl restart docker.service"
alias docker-disable="sudo systemctl disable docker.service"
alias docker-enable="sudo systemctl enable docker.service"
	
alias plex-stop="sudo systemctl stop plexmediaserver.service"
alias plex-start="sudo systemctl start plexmediaserver.service"
alias plex-status="sudo systemctl status plexmediaserver.service"
alias plex-restart="sudo systemctl restart plexmediaserver.service"
alias plex-disable="sudo systemctl disable plexmediaserver.service"
alias plex-enable="sudo systemctl enable plexmediaserver.service"

alias emby-stop="sudo systemctl stop emby-server.service"
alias emby-start="sudo systemctl start emby-server.service"
alias emby-status="sudo systemctl status emby-server.service"
alias emby-restart="sudo systemctl restart emby-server.service"
alias emby-disable="sudo systemctl disable emby-server.service"
alias emby-enable="sudo systemctl enable emby-server.service"

alias ftp-stop="sudo systemctl stop ftpd.service"
alias ftp-start="sudo systemctl start ftpd.service"
alias ftp-status="sudo systemctl status ftpd.service"
alias ftp-restart="sudo systemctl restart ftpd.service"
alias ftp-disable="sudo systemctl disable ftpd.service"
alias ftp-enable="sudo systemctl enable ftpd.service"

alias uftp-stop="sudo systemctl stop uftp.service"
alias uftp-start="sudo systemctl start uftp.service"
alias uftp-status="sudo systemctl status uftp.service"
alias uftp-restart="sudo systemctl restart uftp.service"
alias uftp-disable="sudo systemctl disable uftp.service"
alias uftp-enable="sudo systemctl enable uftp.service"
